chore: remove unneeded type: module marker
netlify/zip-it-and-ship-it pull request #1488
Opened 2023-07-04 15:04 UTC by Skn0tt

🎉 Thanks for submitting a pull request! 🎉

#### Summary

In our tests, we had two instances of a `{ "type": "module" }` package.json being emitted, so that the resulting file is interpreted as ESM. Since outputted filename is already `.mjs`, this is redundant.

This PR removes that `package.json` to remove confusion.

---

For us to review and ship your PR efficiently, please perform the following steps:

- [ ] Open a [bug/issue](https://github.com/netlify/zip-it-and-ship-it/issues/new/choose) before writing your code 🧑‍💻.
      This ensures we can discuss the changes and get feedback from everyone that should be involved. If you\`re fixing
      a typo or something that\`s on fire 🔥 (e.g. incident related), you can skip this step.
- [ ] Read the [contribution guidelines](../CONTRIBUTING.md) 📖. This ensures your code follows our style guide and
      passes our tests.
- [ ] Update or add tests (if any source code was changed or added) 🧪
- [ ] Update or add documentation (if features were changed or added) 📝
- [ ] Make sure the status checks below are successful ✅

**A picture of a cute animal (not mandatory, but encouraged)**

2023-07-05 12:22 UTC, eduardoboucas requested changes

2023-07-05 12:22 UTC, eduardoboucas commented on tests/main.test.ts
> +  testMany.only(
```suggestion
  testMany(
```

2023-07-07 10:18 UTC, danez approved these changes

2023-10-16 09:53 UTC, lukasholzer approved these changes

2023-10-16 10:04 UTC, merged